sonar.projectKey=bookstore-app
sonar.projectName=BookStore Application
sonar.host.url=http://localhost:9000
sonar.token=squ_a59e5dc4d7e6990d2f407b0479e123e78599a081
sonar.sources=BookStore
sonar.tests=BookStore.Tests
sonar.cs.opencover.reportsPaths=coverage.xml
sonar.coverage.exclusions=**Test*.cs,**/*.json,Program.cs